import { Injectable } from '@angular/core';

export class EuropeanUnion {
    nameAr: string;
    nameEn: string;
    population: number;
    area: number;
    capitalAr: string;
    capitalEn: string;
    Accession: number;
}

let europeanUnion: EuropeanUnion[] = [{
    nameAr: "النمسا",
    nameEn: "Austria",
    population: 8451900,
    area: 83855,
    capitalAr: "فيينا",
    capitalEn: "Vienna",
    Accession: 1995
}, {
    nameAr: "بلجيكا",
    nameEn: "Belgium",
    population: 11161600,
    area: 30528,
    capitalAr: "بروكسل",
    capitalEn: "Brussels",
    Accession: 1957
}, {
    nameAr: "بلغاريا",
    nameEn: "Bulgaria",
    population: 7284600,
    area: 110994,
    capitalAr: "صوفيا",
    capitalEn: "Sofia",
    Accession: 2007
}, {
    nameAr: "كرواتيا",
    nameEn: "Croatia",
    population: 4262100,
    area: 56594,
    capitalAr: "زغرب",
    capitalEn: "Zagreb",
    Accession: 2013
}, {
    nameAr: "قبرص",
    nameEn: "Cyprus",
    population: 865900,
    area: 9251,
    capitalAr: "نيقوسيا",
    capitalEn: "Nicosia",
    Accession: 2004
}, {
    nameAr: "الجمهورية التشيكية",
    nameEn: "Czech Republic",
    population: 10516100,
    area: 78866,
    capitalAr: "براغ",
    capitalEn: "Prague",
    Accession: 2004
}, {
    nameAr: "الدنمارك",
    nameEn: "Denmark",
    population: 5602600,
    area: 43075,
    capitalAr: "كوبنهاغن",
    capitalEn: "Copenhagen",
    Accession: 1973
}, {
    nameAr: "استونيا",
    nameEn: "Estonia",
    population: 1324800,
    area: 45227,
    capitalAr: "تالين",
    capitalEn: "Tallinn",
    Accession: 2004
}, {
    nameAr: "فنلندا",
    nameEn: "Finland",
    population: 5426700,
    area: 338424,
    capitalAr: "هلسنكي",
    capitalEn: "Helsinki",
    Accession: 1995
}, {
    nameAr: "فرنسا",
    nameEn: "France",
    population: 65633200,
    area: 674843,
    capitalAr: "باريس",
    capitalEn: "Paris",
    Accession: 1957
}, {
    nameAr: "ألمانيا",
    nameEn: "Germany",
    population: 80523700,
    area: 357021,
    capitalAr: "البرلينية",
    capitalEn: "Berlin",
    Accession: 1957
}, {
    nameAr: "يونان",
    nameEn: "Greece",
    population: 11062500,
    area: 131990,
    capitalAr: "أثينا",
    capitalEn: "Athens",
    Accession: 1981
}, {
    nameAr: "هنغاريا",
    nameEn: "Hungary",
    population: 9908800,
    area: 93030,
    capitalAr: "بودابست",
    capitalEn: "Budapest",
    Accession: 2004
}, {
    nameAr: "أيرلندا",
    nameEn: "Ireland",
    population: 4591100,
    area: 70273,
    capitalAr: "دبلن",
    capitalEn: "Dublin",
    Accession: 1973
}, {
    nameAr: "إيطاليا",
    nameEn: "Italy",
    population: 59685200,
    area: 301338,
    capitalAr: "روما",
    capitalEn: "Rome",
    Accession: 1957
}, {
    nameAr: "لاتفيا",
    nameEn: "Latvia",
    population: 2023800,
    area: 64589,
    capitalAr: "ريغا",
    capitalEn: "Riga",
    Accession: 2004
}, {
    nameAr: "ليتوانيا",
    nameEn: "Lithuania",
    population: 2971900,
    area: 65200,
    capitalAr: "فيلنيوس",
    capitalEn: "Vilnius",
    Accession: 2004
}, {
    nameAr: "لوكسمبورغ",
    nameEn: "Luxembourg",
    population: 537000,
    area: 2586.4,
    capitalAr: "لوكسمبورغ",
    capitalEn: "Luxembourg",
    Accession: 1957
}, {
    nameAr: "مالطا",
    nameEn: "Malta",
    population: 421400,
    area: 316,
    capitalAr: "فاليتا",
    capitalEn: "Valletta",
    Accession: 2004
}, {
    nameAr: "هولندا",
    nameEn: "Netherlands",
    population: 16779600,
    area: 41543,
    capitalAr: "أمستردام",
    capitalEn: "Amsterdam",
    Accession: 1957
}, {
    nameAr: "بولندا",
    nameEn: "Poland",
    population: 38533300,
    area: 312685,
    capitalAr: "وارسو",
    capitalEn: "Warsaw",
    Accession: 2004
}, {
    nameAr: "البرتغال",
    nameEn: "Portugal",
    population: 10487300,
    area: 92390,
    capitalAr: "لشبونة",
    capitalEn: "Lisbon",
    Accession: 1986
}, {
    nameAr: "رومانيا",
    nameEn: "Romania",
    population: 20057500,
    area: 238391,
    capitalAr: "بوخارست",
    capitalEn: "Bucharest",
    Accession: 2007
}, {
    nameAr: "سلوفاكيا",
    nameEn: "Slovakia",
    population: 5410800,
    area: 49035,
    capitalAr: "براتيسلافا",
    capitalEn: "Bratislava",
    Accession: 2004
}, {
    nameAr: "سلوفينيا",
    nameEn: "Slovenia",
    population: 2058800,
    area: 20273,
    capitalAr: "ليوبليانا",
    capitalEn: "Ljubljana",
    Accession: 2004
}, {
    nameAr: "إسبانيا",
    nameEn: "Spain",
    population: 46704300,
    area: 504030,
    capitalAr: "مدريد",
    capitalEn: "Madrid",
    Accession: 1986
}, {
    nameAr: "السويد",
    nameEn: "Sweden",
    population: 9555900,
    area: 449964,
    capitalAr: "ستوكهولم",
    capitalEn: "Stockholm",
    Accession: 1995
}, {
    nameAr: "المملكة المتحدة",
    nameEn: "United Kingdom",
    population: 63730100,
    area: 243610,
    capitalAr: "لندن",
    capitalEn: "London",
    Accession: 1973
}];

@Injectable()
export class Service {
    getEuropeanUnion() {
        return europeanUnion;
    }
}
